INSERT INTO chileplacer..TypeContextura VALUES ('Delgada','Delgada')
INSERT INTO chileplacer..TypeContextura VALUES ('Mediana','Mediana')
INSERT INTO chileplacer..TypeContextura VALUES ('Atletica','Atletica')
INSERT INTO chileplacer..TypeContextura VALUES ('Robusta','Robusta')
INSERT INTO chileplacer..TypeContextura VALUES ('Voluptuosa','Voluptuosa')

INSERT INTO db_a72b76_chileplacer..TypeContextura VALUES ('Delgada','Delgada')
INSERT INTO db_a72b76_chileplacer..TypeContextura VALUES ('Mediana','Mediana')
INSERT INTO db_a72b76_chileplacer..TypeContextura VALUES ('Atletica','Atletica')
INSERT INTO db_a72b76_chileplacer..TypeContextura VALUES ('Robusta','Robusta')
INSERT INTO db_a72b76_chileplacer..TypeContextura VALUES ('Voluptuosa','Voluptuosa')
