 INSERT INTO chileplacer..TypeEscort VALUES ('Escort Mujeres','Escort Mujeres') 
 INSERT INTO chileplacer..TypeEscort VALUES ('Escort Maduras','Escort Maduras')
 INSERT INTO chileplacer..TypeEscort VALUES ('Escort Lésbicas','Escort Lésbicas')
 INSERT INTO chileplacer..TypeEscort VALUES ('Masajes','Masajes')
 INSERT INTO chileplacer..TypeEscort VALUES ('Chicas Under','Chicas Under')
 INSERT INTO chileplacer..TypeEscort VALUES ('Escort Hombres','Escort Hombres')
 INSERT INTO chileplacer..TypeEscort VALUES ('Escort Gay','Escort Gay')
 INSERT INTO chileplacer..TypeEscort VALUES ('Escort Trans', 'Escort Trans')