INSERT INTO chileplacer..TypeServicesSex VALUES ('Besos en la Boca','Besos en la Boca')
INSERT INTO chileplacer..TypeServicesSex VALUES('Garganta Profunda','Garganta Profunda')
INSERT INTO chileplacer..TypeServicesSex VALUES('Oral sin Preservativo','Oral sin Preservativo')
INSERT INTO chileplacer..TypeServicesSex VALUES('Americana en la Boca','Americana en la Boca')
INSERT INTO chileplacer..TypeServicesSex VALUES('Americana Corporal','Americana Corporal')
INSERT INTO chileplacer..TypeServicesSex VALUES('Rusa','Rusa')
INSERT INTO chileplacer..TypeServicesSex VALUES('Anal','Anal')
INSERT INTO chileplacer..TypeServicesSex VALUES('Masajes','Masajes')
INSERT INTO chileplacer..TypeServicesSex VALUES('Duales (Con otra chica sin interactuar con ella)','Duales (Con otra chica sin interactuar con ella)')
INSERT INTO chileplacer..TypeServicesSex VALUES('Cuadros Plásticos (Lesbianismo interactuando con otra chica)','Cuadros Plásticos (Lesbianismo interactuando con otra chica)')
INSERT INTO chileplacer..TypeServicesSex VALUES('Tríos (con dos hombres)','Tríos (con dos hombres)')
INSERT INTO chileplacer..TypeServicesSex VALUES('Orgías','Orgías')
INSERT INTO chileplacer..TypeServicesSex VALUES('Fantasías','Fantasías')
INSERT INTO chileplacer..TypeServicesSex VALUES('Beso Negro','Beso Negro')
INSERT INTO chileplacer..TypeServicesSex VALUES('Atención a Discapacitados','Atención a Discapacitados')
INSERT INTO chileplacer..TypeServicesSex VALUES('Atención a Mujeres (Lesbianismo)','Atención a Mujeres (Lesbianismo)')
INSERT INTO chileplacer..TypeServicesSex VALUES('Atención a Parejas','Atención a Parejas')
INSERT INTO chileplacer..TypeServicesSex VALUES('Cambio de Rol','Cambio de Rol')
INSERT INTO chileplacer..TypeServicesSex VALUES('Disfraces','Disfraces')
INSERT INTO chileplacer..TypeServicesSex VALUES('Despedidas de Soltero(a)','Despedidas de Soltero(a)')
INSERT INTO chileplacer..TypeServicesSex VALUES('Juguetes Eróticos','Juguetes Eróticos')
INSERT INTO chileplacer..TypeServicesSex VALUES('Dominación','Dominación')
INSERT INTO chileplacer..TypeServicesSex VALUES('Sumisión','Sumisión')
INSERT INTO chileplacer..TypeServicesSex VALUES('Eventos y Cenas','Eventos y Cenas')
INSERT INTO chileplacer..TypeServicesSex VALUES('Viajes','Viajes')



INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES ('Besos en la Boca','Besos en la Boca')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Garganta Profunda','Garganta Profunda')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Oral sin Preservativo','Oral sin Preservativo')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Americana en la Boca','Americana en la Boca')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Americana Corporal','Americana Corporal')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Rusa','Rusa')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Anal','Anal')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Masajes','Masajes')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Duales (Con otra chica sin interactuar con ella)','Duales (Con otra chica sin interactuar con ella)')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Cuadros Plásticos (Lesbianismo interactuando con otra chica)','Cuadros Plásticos (Lesbianismo interactuando con otra chica)')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Tríos (con dos hombres)','Tríos (con dos hombres)')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Orgías','Orgías')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Fantasías','Fantasías')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Beso Negro','Beso Negro')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Atención a Discapacitados','Atención a Discapacitados')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Atención a Mujeres (Lesbianismo)','Atención a Mujeres (Lesbianismo)')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Atención a Parejas','Atención a Parejas')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Cambio de Rol','Cambio de Rol')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Disfraces','Disfraces')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Despedidas de Soltero(a)','Despedidas de Soltero(a)')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Juguetes Eróticos','Juguetes Eróticos')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Dominación','Dominación')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Sumisión','Sumisión')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Eventos y Cenas','Eventos y Cenas')
INSERT INTO db_a72b76_chileplacer..TypeServicesSex VALUES('Viajes','Viajes')
--TRUNCATE TABLE chileplacer..chileplacer..TypeServicesSex

