INSERT INTO TypeServicesSex VALUES ('Besos en la Boca','Besos en la Boca')
INSERT INTO TypeServicesSex VALUES('Garganta Profunda','Garganta Profunda')
INSERT INTO TypeServicesSex VALUES('Oral sin Preservativo','Oral sin Preservativo')
INSERT INTO TypeServicesSex VALUES('Americana en la Boca','Americana en la Boca')
INSERT INTO TypeServicesSex VALUES('Americana Corporal','Americana Corporal')
INSERT INTO TypeServicesSex VALUES('Rusa','Rusa')
INSERT INTO TypeServicesSex VALUES('Anal','Anal')
INSERT INTO TypeServicesSex VALUES('Masajes','Masajes')
INSERT INTO TypeServicesSex VALUES('Duales (Con otra chica sin interactuar con ella)','Duales (Con otra chica sin interactuar con ella)')
INSERT INTO TypeServicesSex VALUES('Cuadros Plásticos (Lesbianismo interactuando con otra chica)','Cuadros Plásticos (Lesbianismo interactuando con otra chica)')
INSERT INTO TypeServicesSex VALUES('Tríos (con dos hombres)','Tríos (con dos hombres)')
INSERT INTO TypeServicesSex VALUES('Orgías','Orgías')
INSERT INTO TypeServicesSex VALUES('Fantasías','Fantasías')
INSERT INTO TypeServicesSex VALUES('Beso Negro','Beso Negro')
INSERT INTO TypeServicesSex VALUES('Atención a Discapacitados','Atención a Discapacitados')
INSERT INTO TypeServicesSex VALUES('Atención a Mujeres (Lesbianismo)','Atención a Mujeres (Lesbianismo)')
INSERT INTO TypeServicesSex VALUES('Atención a Parejas','Atención a Parejas')
INSERT INTO TypeServicesSex VALUES('Cambio de Rol','Cambio de Rol')
INSERT INTO TypeServicesSex VALUES('Disfraces','Disfraces')
INSERT INTO TypeServicesSex VALUES('Despedidas de Soltero(a)','Despedidas de Soltero(a)')
INSERT INTO TypeServicesSex VALUES('Juguetes Eróticos','Juguetes Eróticos')
INSERT INTO TypeServicesSex VALUES('Dominación','Dominación')
INSERT INTO TypeServicesSex VALUES('Sumisión','Sumisión')
INSERT INTO TypeServicesSex VALUES('Eventos y Cenas','Eventos y Cenas')
INSERT INTO TypeServicesSex VALUES('Viajes','Viajes')

--TRUNCATE TABLE chileplacer..TypeServicesSex
